--- 
abstract: Filter and modify output
author: 
  - H.Merijn Brand <h.m.brand@xs4all.nl>
configure_requires: 
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: Author, CPAN::Meta::Converter version 2.133380
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-OutputFilter
provides: 
  Text::OutputFilter: 
    file: OutputFilter.pm
    version: '0.18'
recommends: 
  perl: '5.018001'
requires: 
  Carp: 0
  Test::More: 0
  Test::NoWarnings: 0
  perl: '5.008'
resources: 
  license: http://dev.perl.org/licenses/
  repository: http://repo.or.cz/r/Text-OutputFilter.git
version: '0.18'
