--- #YAML:1.1
name:              Text::OutputFilter
version:           0.14
abstract:          Filter and modify output
license:           perl
author:              
    - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:      Author
distribution_type: module
provides:
    Text::OutputFilter:
        file:      OutputFilter.pm
        version:   0.14
requires:     
    perl:          5.008
    Carp:          0
build_requires:
    perl:          5.008
    Test::Harness: 0
    Test::More:    0
resources:
    license:       http://dev.perl.org/licenses/
meta-spec:
    version:       1.4
    url:           http://module-build.sourceforge.net/META-spec-v1.4.html
