--- #YAML:1.0
name:                Text-OutputFilter
version:             0.11
abstract:            Filter and modify output
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - H.Merijn Brand <h.merijn@procura.nl>
